from pathlib import Path
p=Path('client/src/pages/Home.tsx')
s=p.read_text()
start=s.find('    <section className="surface analysis-result">')
end=s.find('</section>', start)
if start<0 or end<0: raise SystemExit('analysis panel not found')
end += len('</section>')
new='''    <section className="surface analysis-result exact-analysis-panel"><div><div className="section-kicker">Exact FastAPI inference</div><h2 className="section-title">Selected source: {activeAudio === "abnormal" ? "faulty benchmark audio" : activeAudio === "normal" ? "healthy benchmark audio" : uploadedName ?? (recordedUrl ? "local microphone recording" : "select an audio source")}</h2>{analysisResult ? <div className="exact-score-grid"><div><span>MODEL</span><strong>{analysisResult.model.key}</strong></div><div><span>RAW SCORE</span><strong>{analysisResult.score.toFixed(5)}</strong></div><div><span>THRESHOLD · P95</span><strong>{analysisResult.threshold.toFixed(5)}</strong></div><div><span>RATIO</span><strong>{analysisResult.scoreThresholdRatio.toFixed(2)}×</strong></div></div> : <p className="analysis-waiting">Run the exact DCASE checkpoint against a WAV upload to see real inference evidence.</p>}</div><div className="analysis-meter"><span>Reconstruction error / verdict</span><div className="meter-track"><i style={{ width: `${meterWidth}%` }} /></div><strong className={analysisResult?.decision === "Anomaly" ? "danger-text" : ""}>{analysisResult ? analysisResult.decision.toUpperCase() : "WAITING"}</strong>{analysisResult && <small>{analysisResult.frameCount} stacked frames · {analysisResult.reliability}</small>}</div>{analysisResult && <div className="frame-score-strip" aria-label="Frame-level reconstruction score chart">{analysisResult.frameScores.filter((_, index) => index % Math.max(1, Math.floor(analysisResult.frameScores.length / 80)) === 0).map((score, index) => <i key={`${score}-${index}`} style={{ height: `${Math.min(100, Math.max(6, (score / analysisResult.threshold) * 42))}%` }} />)}</div>}<button className="solid-button" onClick={runAnalysis}>{analyzing ? <><Activity size={15} className="animate-pulse" /> Analysing</> : <><Cpu size={15} /> Run exact backend analysis</>}</button></section>'''
s=s[:start]+new+s[end:]
p.write_text(s)
